global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'FreeBSD'
    scrape_interval: 5s
    static_configs:
      - targets: ['139.99.22.56:9100']

  - job_name: 'FreeBSD-VTS'
    scrape_interval: 5s
    static_configs:
      - targets: ['dashboard.doco.dgprasetya.net:9913']

  - job_name: 'Debian'
    scrape_interval: 5s
    static_configs:
      - targets: ['debian:9100']

  - job_name: 'Centos'
    scrape_interval: 5s
    static_configs:
      - targets: ['centos:9100']

  - job_name: 'CentosDua'
    scrape_interval: 5s
    static_configs:
      - targets: ['centosdua:9100']

  - job_name: 'Centos-nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['centos:9113']



alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
